version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/antham/versem
    environment:
      BASH_ENV: /home/circleci/.bashrc
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Install gox
          command: |
            go get github.com/mitchellh/gox
      - run:
          name: Install golang-ci
          command: |
            go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run:
          name: Install vendors
          command: |
            export GO111MODULE=on
            go mod vendor
      - run:
          name: Compile
          command: |
            make compile
      - run:
          name: Run tests
          command: |
            make test-all
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)
