// Code generated by "stringer -type=Version"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNVALIDVERSION-0]
	_ = x[NORELEASE-1]
	_ = x[PATCH-2]
	_ = x[MINOR-3]
	_ = x[MAJOR-4]
}

const _Version_name = "UNVALIDVERSIONNORELEASEPATCHMINORMAJOR"

var _Version_index = [...]uint8{0, 14, 23, 28, 33, 38}

func (i Version) String() string {
	if i < 0 || i >= Version(len(_Version_index)-1) {
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Version_name[_Version_index[i]:_Version_index[i+1]]
}
